on:
  # release:
  #   types: [published]
  workflow_dispatch:

name: AWS

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@master

      - name: Set git env
        run: echo "TAG_NAME=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.11

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install depends
        run: pnpm install --ignore-scripts

      - name: Build
        run: pnpm build
        env:
          VITE_VERSION: ${{ env.TAG_NAME }}
          VITE_V_DATE: $(date +'%Y-%m-%dT%H:%M:%S')
          VITE_PHONE: ${{ secrets.PHONE }}
          VITE_EMAIL: ${{ secrets.EMAIL }}
          VITE_LINKEDIN: ${{ secrets.LINKEDIN }}
          VITE_GITHUB: ${{ vars.GITHUB }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Deploy to S3
        run: aws s3 sync ./dist/ s3://${{ vars.S3_BUCKET }} --delete
